server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/changchangsong/microservicecloud-config.git #GitHub上面的git仓库名字
#          uri: git@github.com:changchangsong/microservicecloud-config.git #此种方式会访问不到数据

